version = 1
SPDX-PackageName = "FoamAdapter"
SPDX-PackageSupplier = "FoamAdapter authors"
SPDX-PackageDownloadLocation = "https://github.com/exasim-project/FoamAdapter"

[[annotations]]
path = [
    ".github/**", "AUTHORS.md",  "doc/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 FoamAdapter authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "CMakePresets.json", ".clang-format", ".clang-tidy", ".pre-commit-config.yaml", "spack.yaml", "REUSE.toml",  ".vscode/**.json", "*.log"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 FoamAdapter authors"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = [
    "test/**",
     "benchmarks/**",
     "tutorials/**",
     ".github/workflows/build.yaml",
     ".github/workflows/static_checks.yaml",
     ".github/workflows/pubkey.gpg",
     ".vscode/c_cpp_properties.json",
     ".vscode/settings.json",
     "CHANGELOG.md",
     "README.md",
     ".gitmodules",
     "environment.yml",
    "CMakePresets.json",
    ".clang-format",
    ".clang-tidy",
    ".pre-commit-config.yaml",
    "spack.yaml",
    "**/case/**",
    "REUSE.toml"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 FoamAdapter authors"
SPDX-License-Identifier = "Unlicense"
